server:
  port: 8090

management:
   security:
      enabled: false
   endpoints:
     web: 
      exposure:
        include: "*"


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
   name: api-gateway
  cloud:
    gateway:
     routes:
     - id: user-management
       uri: lb://user-management
       predicates:
        - Path=/users/**
     - id: merchant-management
       uri: lb://merchant-management
       predicates:
        - Path=/merchants/**


  
